// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: BoxTurtle_CYD

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void GifPop_Animation( lv_obj_t *TargetObject, int delay);


// SCREEN: ui_LaneSelect
void ui_LaneSelect_screen_init(void);
lv_obj_t *ui_LaneSelect;
lv_obj_t *ui_ToolButtonContainer;
void ui_event_BtnSlot0( lv_event_t * e);
lv_obj_t *ui_BtnSlot0;
lv_obj_t *ui_LblSlot0;
void ui_event_BtnSlot1( lv_event_t * e);
lv_obj_t *ui_BtnSlot1;
lv_obj_t *ui_LblSlot1;
void ui_event_BtnSlot2( lv_event_t * e);
lv_obj_t *ui_BtnSlot2;
lv_obj_t *ui_LblSlot2;
void ui_event_BtnSlot3( lv_event_t * e);
lv_obj_t *ui_BtnSlot3;
lv_obj_t *ui_LblSlot3;
lv_obj_t *ui_TempPanel;
lv_obj_t *ui_ImgNozzle;
lv_obj_t *ui_LblNozzle;
lv_obj_t *ui_ImgBed;
lv_obj_t *ui_LblBed;
lv_obj_t *ui_SwitchStatusPanel;
lv_obj_t *ui_LblHub;
lv_obj_t *ui_LblHubStatus;
lv_obj_t *ui_LblTool;
lv_obj_t *ui_LblToolStatus;
lv_obj_t *ui_FuncPanel;
void ui_event_BtnUnload( lv_event_t * e);
lv_obj_t *ui_BtnUnload;
lv_obj_t *ui_Label3;
void ui_event_BtnBrush( lv_event_t * e);
lv_obj_t *ui_BtnBrush;
lv_obj_t *ui_Label4;
void ui_event_BtnCut( lv_event_t * e);
lv_obj_t *ui_BtnCut;
lv_obj_t *ui_Label15;
void ui_event_BtnG32( lv_event_t * e);
lv_obj_t *ui_BtnG32;
lv_obj_t *ui_Label16;
// CUSTOM VARIABLES


// SCREEN: ui_LaneFunctions
void ui_LaneFunctions_screen_init(void);
lv_obj_t *ui_LaneFunctions;
lv_obj_t *ui_PnlFunctions;
void ui_event_LoadTool( lv_event_t * e);
lv_obj_t *ui_LoadTool;
lv_obj_t *ui_LblLoad;
void ui_event_EjectLane( lv_event_t * e);
lv_obj_t *ui_EjectLane;
lv_obj_t *ui_LblEjectLane;
void ui_event_Back( lv_event_t * e);
lv_obj_t *ui_Back;
lv_obj_t *ui_ImgBack;
lv_obj_t *ui_LblBack;
// CUSTOM VARIABLES


// SCREEN: ui_Wait
void ui_Wait_screen_init(void);
lv_obj_t *ui_Wait;
void ui_event_ImgSpool( lv_event_t * e);
lv_obj_t *ui_ImgSpool;
lv_obj_t *ui_LblWaiting;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_img_dsc_t *ui_imgset_255621937[1] = {&ui_img_922480046};
const lv_img_dsc_t *ui_imgset_639896326[12] = {&ui_img_642937331, &ui_img_642936306, &ui_img_539412392, &ui_img_542316787, &ui_img_642943729, &ui_img_642942704, &ui_img_642941679, &ui_img_642940654, &ui_img_642948077, &ui_img_642947052, &ui_img_642946043, &ui_img_642945018};
const lv_img_dsc_t *ui_imgset_print_bar[2] = {&ui_img_print_bar1_png, &ui_img_print_bar2_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void GifPop_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 1000);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_x );
lv_anim_set_values(&PropertyAnimation_0, -100, 10 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_overshoot);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 1000);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
lv_anim_start(&PropertyAnimation_0);
ui_anim_user_data_t *PropertyAnimation_1_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_1_user_data->target = TargetObject;
PropertyAnimation_1_user_data->val = -1;
lv_anim_t PropertyAnimation_1;
lv_anim_init(&PropertyAnimation_1);
lv_anim_set_time(&PropertyAnimation_1, 1000);
lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_y );
lv_anim_set_values(&PropertyAnimation_1, 58, -10 );
lv_anim_set_path_cb( &PropertyAnimation_1, lv_anim_path_ease_in);
lv_anim_set_delay( &PropertyAnimation_1, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_1, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_1, 1000);
lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
lv_anim_set_early_apply( &PropertyAnimation_1, false );
lv_anim_start(&PropertyAnimation_1);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_BtnSlot0( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      SelSlot0( e );
}
}

void ui_event_BtnSlot1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      SelSlot1( e );
}
}

void ui_event_BtnSlot2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      SelSlot2( e );
}
}

void ui_event_BtnSlot3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      SelSlot3( e );
}
}

void ui_event_BtnUnload( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      CallUnload( e );
}
}

void ui_event_BtnBrush( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      CallAfcBrush( e );
}
}

void ui_event_BtnCut( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      CallAfcCut( e );
}
}

void ui_event_BtnG32( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      CallG32Macro( e );
}
}

void ui_event_LoadTool( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      LoadTool( e );
}
}

void ui_event_EjectLane( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      EjectLane( e );
}
}

void ui_event_Back( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_LaneSelect, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_LaneSelect_screen_init);
}
}

void ui_event_ImgSpool( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_LaneSelect, LV_SCR_LOAD_ANIM_NONE, 0, 1000, &ui_LaneSelect_screen_init);
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_LaneSelect_screen_init();
ui_LaneFunctions_screen_init();
ui_Wait_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_LaneSelect);
}
