// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: BoxTurtle_CYD

#ifndef _BOXTURTLE_CYD_UI_H
#define _BOXTURTLE_CYD_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

void GifPop_Animation( lv_obj_t *TargetObject, int delay);

// SCREEN: ui_LaneSelect
void ui_LaneSelect_screen_init(void);
extern lv_obj_t *ui_LaneSelect;
extern lv_obj_t *ui_ToolButtonContainer;
void ui_event_BtnSlot0( lv_event_t * e);
extern lv_obj_t *ui_BtnSlot0;
extern lv_obj_t *ui_LblSlot0;
void ui_event_BtnSlot1( lv_event_t * e);
extern lv_obj_t *ui_BtnSlot1;
extern lv_obj_t *ui_LblSlot1;
void ui_event_BtnSlot2( lv_event_t * e);
extern lv_obj_t *ui_BtnSlot2;
extern lv_obj_t *ui_LblSlot2;
void ui_event_BtnSlot3( lv_event_t * e);
extern lv_obj_t *ui_BtnSlot3;
extern lv_obj_t *ui_LblSlot3;
extern lv_obj_t *ui_TempPanel;
extern lv_obj_t *ui_ImgNozzle;
extern lv_obj_t *ui_LblNozzle;
extern lv_obj_t *ui_ImgBed;
extern lv_obj_t *ui_LblBed;
extern lv_obj_t *ui_SwitchStatusPanel;
extern lv_obj_t *ui_LblHub;
extern lv_obj_t *ui_LblHubStatus;
extern lv_obj_t *ui_LblTool;
extern lv_obj_t *ui_LblToolStatus;
extern lv_obj_t *ui_FuncPanel;
void ui_event_BtnUnload( lv_event_t * e);
extern lv_obj_t *ui_BtnUnload;
extern lv_obj_t *ui_Label3;
void ui_event_BtnBrush( lv_event_t * e);
extern lv_obj_t *ui_BtnBrush;
extern lv_obj_t *ui_Label4;
void ui_event_BtnCut( lv_event_t * e);
extern lv_obj_t *ui_BtnCut;
extern lv_obj_t *ui_Label15;
void ui_event_BtnG32( lv_event_t * e);
extern lv_obj_t *ui_BtnG32;
extern lv_obj_t *ui_Label16;
// CUSTOM VARIABLES

// SCREEN: ui_LaneFunctions
void ui_LaneFunctions_screen_init(void);
extern lv_obj_t *ui_LaneFunctions;
extern lv_obj_t *ui_PnlFunctions;
void ui_event_LoadTool( lv_event_t * e);
extern lv_obj_t *ui_LoadTool;
extern lv_obj_t *ui_LblLoad;
void ui_event_EjectLane( lv_event_t * e);
extern lv_obj_t *ui_EjectLane;
extern lv_obj_t *ui_LblEjectLane;
void ui_event_Back( lv_event_t * e);
extern lv_obj_t *ui_Back;
extern lv_obj_t *ui_ImgBack;
extern lv_obj_t *ui_LblBack;
// CUSTOM VARIABLES

// SCREEN: ui_Wait
void ui_Wait_screen_init(void);
extern lv_obj_t *ui_Wait;
void ui_event_ImgSpool( lv_event_t * e);
extern lv_obj_t *ui_ImgSpool;
extern lv_obj_t *ui_LblWaiting;
// CUSTOM VARIABLES

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_filament_png);   // assets/filament.png
LV_IMG_DECLARE( ui_img_bed_png);   // assets/bed.png
LV_IMG_DECLARE( ui_img_1470730272);   // assets/arrow-left.png
LV_IMG_DECLARE( ui_img_922480046);   // assets/2602507-200.png
LV_IMG_DECLARE( ui_img_642937331);   // assets/extruder-0.png
LV_IMG_DECLARE( ui_img_642936306);   // assets/extruder-1.png
LV_IMG_DECLARE( ui_img_539412392);   // assets/extruder-10.png
LV_IMG_DECLARE( ui_img_542316787);   // assets/extruder-11.png
LV_IMG_DECLARE( ui_img_642943729);   // assets/extruder-2.png
LV_IMG_DECLARE( ui_img_642942704);   // assets/extruder-3.png
LV_IMG_DECLARE( ui_img_642941679);   // assets/extruder-4.png
LV_IMG_DECLARE( ui_img_642940654);   // assets/extruder-5.png
LV_IMG_DECLARE( ui_img_642948077);   // assets/extruder-6.png
LV_IMG_DECLARE( ui_img_642947052);   // assets/extruder-7.png
LV_IMG_DECLARE( ui_img_642946043);   // assets/extruder-8.png
LV_IMG_DECLARE( ui_img_642945018);   // assets/extruder-9.png
LV_IMG_DECLARE( ui_img_print_bar1_png);   // assets/print_bar1.png
LV_IMG_DECLARE( ui_img_print_bar2_png);   // assets/print_bar2.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
