// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: BoxTurtle_CYD

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void SelSlot0(lv_event_t * e);
void SelSlot1(lv_event_t * e);
void SelSlot2(lv_event_t * e);
void SelSlot3(lv_event_t * e);
void CallUnload(lv_event_t * e);
void CallAfcBrush(lv_event_t * e);
void CallAfcCut(lv_event_t * e);
void CallG32Macro(lv_event_t * e);
void LoadTool(lv_event_t * e);
void EjectLane(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
