// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: BoxTurtleCYD

#include "ui.h"

#include "ui_functions.h"


void SelSlot0(lv_event_t * e)
{
	selected = 0;
	_ui_screen_change(&ui_LaneFunctions, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_LaneFunctions_screen_init);
}

void SelSlot1(lv_event_t * e)
{
	selected = 1;
	_ui_screen_change(&ui_LaneFunctions, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_LaneFunctions_screen_init);
}

void SelSlot2(lv_event_t * e)
{
	selected = 2;
	_ui_screen_change(&ui_LaneFunctions, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_LaneFunctions_screen_init);
}

void SelSlot3(lv_event_t * e)
{
	selected = 3;
	_ui_screen_change(&ui_LaneFunctions, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_LaneFunctions_screen_init);
}

void CallUnload(lv_event_t * e)
{
	_ui_screen_change( &ui_Wait, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Wait_screen_init);
	DoUnload();
	_ui_screen_change( &ui_LaneSelect, LV_SCR_LOAD_ANIM_NONE, 0, 1000, &ui_LaneSelect_screen_init);
}

void CallAfcBrush(lv_event_t * e)
{
	_ui_screen_change( &ui_Wait, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Wait_screen_init);
	afcBrushCall();
	_ui_screen_change( &ui_LaneSelect, LV_SCR_LOAD_ANIM_NONE, 0, 1000, &ui_LaneSelect_screen_init);
}

void CallAfcCut(lv_event_t * e)
{
	_ui_screen_change( &ui_Wait, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Wait_screen_init);
	afcCutCall();
	_ui_screen_change( &ui_LaneSelect, LV_SCR_LOAD_ANIM_NONE, 0, 1000, &ui_LaneSelect_screen_init);
}

void LoadTool(lv_event_t * e)
{
	DoLoadTool(legMapTool[selected]);
	_ui_screen_change( &ui_LaneSelect, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_LaneSelect_screen_init);
}

void EjectLane(lv_event_t * e)
{
	DoEjectLane(legLane[selected]);
	_ui_screen_change( &ui_LaneSelect, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_LaneSelect_screen_init);
}

void CallG32Macro(lv_event_t * e)
{
	_ui_screen_change( &ui_Wait, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Wait_screen_init);
	g32Call();
	_ui_screen_change( &ui_LaneSelect, LV_SCR_LOAD_ANIM_NONE, 0, 1000, &ui_LaneSelect_screen_init);
}
