// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: BoxTurtle_CYD

#include "../ui.h"

void ui_LaneFunctions_screen_init(void)
{
ui_LaneFunctions = lv_obj_create(NULL);
lv_obj_clear_flag( ui_LaneFunctions, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_PnlFunctions = lv_obj_create(ui_LaneFunctions);
lv_obj_set_width( ui_PnlFunctions, 320);
lv_obj_set_height( ui_PnlFunctions, 60);
lv_obj_set_align( ui_PnlFunctions, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_PnlFunctions, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LoadTool = lv_btn_create(ui_PnlFunctions);
lv_obj_set_width( ui_LoadTool, 100);
lv_obj_set_height( ui_LoadTool, 50);
lv_obj_set_align( ui_LoadTool, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_LoadTool, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_LoadTool, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_LoadTool, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LoadTool, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LblLoad = lv_label_create(ui_LoadTool);
lv_obj_set_width( ui_LblLoad, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LblLoad, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LblLoad, LV_ALIGN_CENTER );
lv_label_set_text(ui_LblLoad,"Load\nLane");
lv_obj_set_style_text_align(ui_LblLoad, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_EjectLane = lv_btn_create(ui_PnlFunctions);
lv_obj_set_width( ui_EjectLane, 100);
lv_obj_set_height( ui_EjectLane, 50);
lv_obj_set_align( ui_EjectLane, LV_ALIGN_RIGHT_MID );
lv_obj_add_flag( ui_EjectLane, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_EjectLane, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_EjectLane, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_EjectLane, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LblEjectLane = lv_label_create(ui_EjectLane);
lv_obj_set_width( ui_LblEjectLane, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LblEjectLane, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LblEjectLane, LV_ALIGN_CENTER );
lv_label_set_text(ui_LblEjectLane,"Eject\nLane");
lv_obj_set_style_text_align(ui_LblEjectLane, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Back = lv_btn_create(ui_LaneFunctions);
lv_obj_set_width( ui_Back, 100);
lv_obj_set_height( ui_Back, 50);
lv_obj_set_align( ui_Back, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_Back, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Back, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Back, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Back, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImgBack = lv_img_create(ui_Back);
lv_img_set_src(ui_ImgBack, &ui_img_1470730272);
lv_obj_set_width( ui_ImgBack, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImgBack, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImgBack, -28 );
lv_obj_set_y( ui_ImgBack, 1 );
lv_obj_set_align( ui_ImgBack, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImgBack, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImgBack, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LblBack = lv_label_create(ui_Back);
lv_obj_set_width( ui_LblBack, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LblBack, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LblBack, 2 );
lv_obj_set_y( ui_LblBack, 1 );
lv_obj_set_align( ui_LblBack, LV_ALIGN_CENTER );
lv_label_set_text(ui_LblBack,"Back");

lv_obj_add_event_cb(ui_LoadTool, ui_event_LoadTool, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_EjectLane, ui_event_EjectLane, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Back, ui_event_Back, LV_EVENT_ALL, NULL);

}
