// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: BoxTurtle_CYD

#include "../ui.h"

void ui_LaneSelect_screen_init(void)
{
ui_LaneSelect = lv_obj_create(NULL);
lv_obj_clear_flag( ui_LaneSelect, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ToolButtonContainer = lv_obj_create(ui_LaneSelect);
lv_obj_remove_style_all(ui_ToolButtonContainer);
lv_obj_set_width( ui_ToolButtonContainer, 320);
lv_obj_set_height( ui_ToolButtonContainer, 65);
lv_obj_set_align( ui_ToolButtonContainer, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_ToolButtonContainer,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_ToolButtonContainer, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_SPACE_EVENLY);
lv_obj_clear_flag( ui_ToolButtonContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_BtnSlot0 = lv_btn_create(ui_ToolButtonContainer);
lv_obj_set_width( ui_BtnSlot0, 60);
lv_obj_set_height( ui_BtnSlot0, 60);
lv_obj_set_x( ui_BtnSlot0, -150 );
lv_obj_set_y( ui_BtnSlot0, 0 );
lv_obj_set_align( ui_BtnSlot0, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BtnSlot0, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BtnSlot0, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_BtnSlot0, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BtnSlot0, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LblSlot0 = lv_label_create(ui_BtnSlot0);
lv_obj_set_width( ui_LblSlot0, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LblSlot0, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LblSlot0, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_LblSlot0,LV_LABEL_LONG_SCROLL_CIRCULAR);
lv_label_set_text(ui_LblSlot0,"Slot0\nTx");
lv_label_set_recolor(ui_LblSlot0,"true");
lv_obj_set_style_text_align(ui_LblSlot0, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LblSlot0, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BtnSlot1 = lv_btn_create(ui_ToolButtonContainer);
lv_obj_set_width( ui_BtnSlot1, 60);
lv_obj_set_height( ui_BtnSlot1, 60);
lv_obj_set_x( ui_BtnSlot1, -50 );
lv_obj_set_y( ui_BtnSlot1, 0 );
lv_obj_set_align( ui_BtnSlot1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BtnSlot1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BtnSlot1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_BtnSlot1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BtnSlot1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LblSlot1 = lv_label_create(ui_BtnSlot1);
lv_obj_set_width( ui_LblSlot1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LblSlot1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LblSlot1, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_LblSlot1,LV_LABEL_LONG_SCROLL_CIRCULAR);
lv_label_set_text(ui_LblSlot1,"Slot1	\nTx");
lv_label_set_recolor(ui_LblSlot1,"true");
lv_obj_set_style_text_align(ui_LblSlot1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LblSlot1, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BtnSlot2 = lv_btn_create(ui_ToolButtonContainer);
lv_obj_set_width( ui_BtnSlot2, 60);
lv_obj_set_height( ui_BtnSlot2, 60);
lv_obj_set_x( ui_BtnSlot2, 50 );
lv_obj_set_y( ui_BtnSlot2, 0 );
lv_obj_set_align( ui_BtnSlot2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BtnSlot2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BtnSlot2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_BtnSlot2, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BtnSlot2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LblSlot2 = lv_label_create(ui_BtnSlot2);
lv_obj_set_width( ui_LblSlot2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LblSlot2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LblSlot2, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_LblSlot2,LV_LABEL_LONG_SCROLL_CIRCULAR);
lv_label_set_text(ui_LblSlot2,"Slot2\nTx");
lv_label_set_recolor(ui_LblSlot2,"true");
lv_obj_set_style_text_align(ui_LblSlot2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LblSlot2, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BtnSlot3 = lv_btn_create(ui_ToolButtonContainer);
lv_obj_set_width( ui_BtnSlot3, 60);
lv_obj_set_height( ui_BtnSlot3, 60);
lv_obj_set_x( ui_BtnSlot3, 150 );
lv_obj_set_y( ui_BtnSlot3, 0 );
lv_obj_set_align( ui_BtnSlot3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BtnSlot3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BtnSlot3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_BtnSlot3, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BtnSlot3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LblSlot3 = lv_label_create(ui_BtnSlot3);
lv_obj_set_width( ui_LblSlot3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LblSlot3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LblSlot3, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_LblSlot3,LV_LABEL_LONG_SCROLL_CIRCULAR);
lv_label_set_text(ui_LblSlot3,"Slot3\nTx");
lv_label_set_recolor(ui_LblSlot3,"true");
lv_obj_set_style_text_align(ui_LblSlot3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LblSlot3, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TempPanel = lv_obj_create(ui_LaneSelect);
lv_obj_set_width( ui_TempPanel, 70);
lv_obj_set_height( ui_TempPanel, 70);
lv_obj_set_align( ui_TempPanel, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_clear_flag( ui_TempPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ImgNozzle = lv_img_create(ui_TempPanel);
lv_img_set_src(ui_ImgNozzle, &ui_img_filament_png);
lv_obj_set_width( ui_ImgNozzle, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImgNozzle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImgNozzle, -20 );
lv_obj_set_y( ui_ImgNozzle, -15 );
lv_obj_set_align( ui_ImgNozzle, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImgNozzle, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImgNozzle, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LblNozzle = lv_label_create(ui_TempPanel);
lv_obj_set_width( ui_LblNozzle, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LblNozzle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LblNozzle, 10 );
lv_obj_set_y( ui_LblNozzle, -15 );
lv_obj_set_align( ui_LblNozzle, LV_ALIGN_CENTER );
lv_label_set_text(ui_LblNozzle,"0	");

ui_ImgBed = lv_img_create(ui_TempPanel);
lv_img_set_src(ui_ImgBed, &ui_img_bed_png);
lv_obj_set_width( ui_ImgBed, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImgBed, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImgBed, -20 );
lv_obj_set_y( ui_ImgBed, 15 );
lv_obj_set_align( ui_ImgBed, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImgBed, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImgBed, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LblBed = lv_label_create(ui_TempPanel);
lv_obj_set_width( ui_LblBed, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LblBed, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LblBed, 10 );
lv_obj_set_y( ui_LblBed, 15 );
lv_obj_set_align( ui_LblBed, LV_ALIGN_CENTER );
lv_label_set_text(ui_LblBed,"0");

ui_SwitchStatusPanel = lv_obj_create(ui_LaneSelect);
lv_obj_set_width( ui_SwitchStatusPanel, 320);
lv_obj_set_height( ui_SwitchStatusPanel, 30);
lv_obj_set_x( ui_SwitchStatusPanel, 0 );
lv_obj_set_y( ui_SwitchStatusPanel, 70 );
lv_obj_set_align( ui_SwitchStatusPanel, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_SwitchStatusPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LblHub = lv_label_create(ui_SwitchStatusPanel);
lv_obj_set_width( ui_LblHub, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LblHub, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LblHub, -10 );
lv_obj_set_y( ui_LblHub, 0 );
lv_obj_set_align( ui_LblHub, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_LblHub,"Hub:");

ui_LblHubStatus = lv_label_create(ui_SwitchStatusPanel);
lv_obj_set_width( ui_LblHubStatus, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LblHubStatus, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LblHubStatus, 35 );
lv_obj_set_y( ui_LblHubStatus, 0 );
lv_obj_set_align( ui_LblHubStatus, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_LblHubStatus,"Unloaded");

ui_LblTool = lv_label_create(ui_SwitchStatusPanel);
lv_obj_set_width( ui_LblTool, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LblTool, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LblTool, -70 );
lv_obj_set_y( ui_LblTool, 0 );
lv_obj_set_align( ui_LblTool, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_LblTool,"Tool:");

ui_LblToolStatus = lv_label_create(ui_SwitchStatusPanel);
lv_obj_set_width( ui_LblToolStatus, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LblToolStatus, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LblToolStatus, 10 );
lv_obj_set_y( ui_LblToolStatus, 0 );
lv_obj_set_align( ui_LblToolStatus, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_LblToolStatus,"Unloaded");

ui_FuncPanel = lv_obj_create(ui_LaneSelect);
lv_obj_set_width( ui_FuncPanel, 240);
lv_obj_set_height( ui_FuncPanel, 120);
lv_obj_set_align( ui_FuncPanel, LV_ALIGN_BOTTOM_LEFT );
lv_obj_set_flex_flow(ui_FuncPanel,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_FuncPanel, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_EVENLY);
lv_obj_clear_flag( ui_FuncPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_BtnUnload = lv_btn_create(ui_FuncPanel);
lv_obj_set_width( ui_BtnUnload, 80);
lv_obj_set_height( ui_BtnUnload, 40);
lv_obj_set_x( ui_BtnUnload, -101 );
lv_obj_set_y( ui_BtnUnload, -12 );
lv_obj_set_align( ui_BtnUnload, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_BtnUnload, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BtnUnload, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_BtnUnload, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BtnUnload, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label3 = lv_label_create(ui_BtnUnload);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 100
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"Unload");

ui_BtnBrush = lv_btn_create(ui_FuncPanel);
lv_obj_set_width( ui_BtnBrush, 80);
lv_obj_set_height( ui_BtnBrush, 40);
lv_obj_add_flag( ui_BtnBrush, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BtnBrush, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_BtnBrush, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BtnBrush, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label4 = lv_label_create(ui_BtnBrush);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"AFC Brush");

ui_BtnCut = lv_btn_create(ui_FuncPanel);
lv_obj_set_width( ui_BtnCut, 80);
lv_obj_set_height( ui_BtnCut, 40);
lv_obj_set_x( ui_BtnCut, -70 );
lv_obj_set_y( ui_BtnCut, 0 );
lv_obj_set_align( ui_BtnCut, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_BtnCut, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BtnCut, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_BtnCut, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BtnCut, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label15 = lv_label_create(ui_BtnCut);
lv_obj_set_width( ui_Label15, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label15, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label15, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label15,"AFC Cut");

ui_BtnG32 = lv_btn_create(ui_FuncPanel);
lv_obj_set_width( ui_BtnG32, 80);
lv_obj_set_height( ui_BtnG32, 40);
lv_obj_set_x( ui_BtnG32, 70 );
lv_obj_set_y( ui_BtnG32, 0 );
lv_obj_set_align( ui_BtnG32, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_BtnG32, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BtnG32, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_BtnG32, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BtnG32, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label16 = lv_label_create(ui_BtnG32);
lv_obj_set_width( ui_Label16, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label16, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label16, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label16,"G32");

lv_obj_add_event_cb(ui_BtnSlot0, ui_event_BtnSlot0, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BtnSlot1, ui_event_BtnSlot1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BtnSlot2, ui_event_BtnSlot2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BtnSlot3, ui_event_BtnSlot3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BtnUnload, ui_event_BtnUnload, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BtnBrush, ui_event_BtnBrush, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BtnCut, ui_event_BtnCut, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BtnG32, ui_event_BtnG32, LV_EVENT_ALL, NULL);

}
