// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: BoxTurtle_CYD

#include "../ui.h"

void ui_Wait_screen_init(void)
{
ui_Wait = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Wait, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ImgSpool = lv_img_create(ui_Wait);
lv_img_set_src(ui_ImgSpool, &ui_img_922480046);
lv_obj_set_width( ui_ImgSpool, lv_pct(100));
lv_obj_set_height( ui_ImgSpool, lv_pct(100));
lv_obj_set_align( ui_ImgSpool, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImgSpool, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImgSpool, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_img_set_zoom(ui_ImgSpool,300);
lv_obj_set_scrollbar_mode(ui_ImgSpool, LV_SCROLLBAR_MODE_OFF);

ui_LblWaiting = lv_label_create(ui_Wait);
lv_obj_set_width( ui_LblWaiting, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LblWaiting, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LblWaiting, LV_ALIGN_CENTER );
lv_label_set_text(ui_LblWaiting,"waiting....");
lv_obj_set_style_text_font(ui_LblWaiting, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_ImgSpool, ui_event_ImgSpool, LV_EVENT_ALL, NULL);

}
