// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: BoxTurtle

#ifndef _BOXTURTLE_UI_H
#define _BOXTURTLE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "../../lib/lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label7;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Label5;

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
