// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: BoxTurtle

#include "../ui.h"

void ui_CurrentLaneToggle_screen_init(void)
{
    ui_CurrentLaneToggle = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_CurrentLaneToggle, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel3 = lv_obj_create(ui_CurrentLaneToggle);
    lv_obj_set_width(ui_Panel3, 254);
    lv_obj_set_height(ui_Panel3, 98);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ActivateLane = lv_btn_create(ui_Panel3);
    lv_obj_set_width(ui_ActivateLane, 100);
    lv_obj_set_height(ui_ActivateLane, 50);
    lv_obj_set_align(ui_ActivateLane, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_ActivateLane, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ActivateLane, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ActivateLaneLabel = lv_label_create(ui_ActivateLane);
    lv_obj_set_width(ui_ActivateLaneLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ActivateLaneLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ActivateLaneLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ActivateLaneLabel, "Activate\n  Lane");

    ui_EjectLane = lv_btn_create(ui_Panel3);
    lv_obj_set_width(ui_EjectLane, 100);
    lv_obj_set_height(ui_EjectLane, 50);
    lv_obj_set_align(ui_EjectLane, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_EjectLane, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_EjectLane, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_EjectLaneLabel = lv_label_create(ui_EjectLane);
    lv_obj_set_width(ui_EjectLaneLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_EjectLaneLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_EjectLaneLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_EjectLaneLabel, "Eject Lane");

    ui_Button10 = lv_btn_create(ui_CurrentLaneToggle);
    lv_obj_set_width(ui_Button10, 100);
    lv_obj_set_height(ui_Button10, 50);
    lv_obj_set_x(ui_Button10, -261);
    lv_obj_set_y(ui_Button10, 56);
    lv_obj_set_align(ui_Button10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button10, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image6 = lv_img_create(ui_Button10);
    lv_img_set_src(ui_Image6, &ui_img_1470730272);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image6, -28);
    lv_obj_set_y(ui_Image6, 1);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label23 = lv_label_create(ui_Button10);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label23, 2);
    lv_obj_set_y(ui_Label23, 1);
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "Back");

    lv_obj_add_event_cb(ui_Button10, ui_event_Button10, LV_EVENT_ALL, NULL);

}
