// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: BoxTurtle

#include "../ui.h"

void ui_GeneralControl_screen_init(void)
{
    ui_GeneralControl = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_GeneralControl, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel5 = lv_obj_create(ui_GeneralControl);
    lv_obj_set_width(ui_Panel5, 550);
    lv_obj_set_height(ui_Panel5, 150);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AFCBrush = lv_btn_create(ui_Panel5);
    lv_obj_set_width(ui_AFCBrush, 100);
    lv_obj_set_height(ui_AFCBrush, 50);
    lv_obj_add_flag(ui_AFCBrush, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_AFCBrush, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_AFCBrush, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Blue);
    ui_object_set_themeable_style_property(ui_AFCBrush, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Blue);

    ui_Label7 = lv_label_create(ui_AFCBrush);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "AFC Brush");

    ui_AFCCut = lv_btn_create(ui_Panel5);
    lv_obj_set_width(ui_AFCCut, 100);
    lv_obj_set_height(ui_AFCCut, 50);
    lv_obj_set_x(ui_AFCCut, -70);
    lv_obj_set_y(ui_AFCCut, 0);
    lv_obj_set_align(ui_AFCCut, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_AFCCut, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_AFCCut, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_AFCCut, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Blue);
    ui_object_set_themeable_style_property(ui_AFCCut, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Blue);

    ui_Label8 = lv_label_create(ui_AFCCut);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "AFC Cut");

    ui_AFCKick = lv_btn_create(ui_Panel5);
    lv_obj_set_width(ui_AFCKick, 100);
    lv_obj_set_height(ui_AFCKick, 50);
    lv_obj_set_x(ui_AFCKick, 70);
    lv_obj_set_y(ui_AFCKick, 0);
    lv_obj_set_align(ui_AFCKick, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_AFCKick, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_AFCKick, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_AFCKick, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Blue);
    ui_object_set_themeable_style_property(ui_AFCKick, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Blue);

    ui_Label9 = lv_label_create(ui_AFCKick);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "AFC Kick");

    ui_AFCPark = lv_btn_create(ui_Panel5);
    lv_obj_set_width(ui_AFCPark, 100);
    lv_obj_set_height(ui_AFCPark, 50);
    lv_obj_set_align(ui_AFCPark, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_AFCPark, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_AFCPark, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_AFCPark, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Blue);
    ui_object_set_themeable_style_property(ui_AFCPark, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Blue);

    ui_Label10 = lv_label_create(ui_AFCPark);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "AFC Park");

    ui_AFCPoop = lv_btn_create(ui_Panel5);
    lv_obj_set_width(ui_AFCPoop, 100);
    lv_obj_set_height(ui_AFCPoop, 50);
    lv_obj_set_align(ui_AFCPoop, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_AFCPoop, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_AFCPoop, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_AFCPoop, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Blue);
    ui_object_set_themeable_style_property(ui_AFCPoop, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Blue);

    ui_Label11 = lv_label_create(ui_AFCPoop);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "AFC Poop");

    ui_BTPrep = lv_btn_create(ui_Panel5);
    lv_obj_set_width(ui_BTPrep, 100);
    lv_obj_set_height(ui_BTPrep, 50);
    lv_obj_set_x(ui_BTPrep, -70);
    lv_obj_set_y(ui_BTPrep, 0);
    lv_obj_set_align(ui_BTPrep, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_BTPrep, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BTPrep, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_BTPrep, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Blue);
    ui_object_set_themeable_style_property(ui_BTPrep, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Blue);

    ui_Label12 = lv_label_create(ui_BTPrep);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "BT Prep");

    ui_BTToolUnload = lv_btn_create(ui_Panel5);
    lv_obj_set_width(ui_BTToolUnload, 100);
    lv_obj_set_height(ui_BTToolUnload, 50);
    lv_obj_set_x(ui_BTToolUnload, 70);
    lv_obj_set_y(ui_BTToolUnload, 0);
    lv_obj_set_align(ui_BTToolUnload, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_BTToolUnload, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BTToolUnload, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_BTToolUnload, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Blue);
    ui_object_set_themeable_style_property(ui_BTToolUnload, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Blue);

    ui_Label13 = lv_label_create(ui_BTToolUnload);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "BT Tool\nUnload");

    ui_Button11 = lv_btn_create(ui_Panel5);
    lv_obj_set_width(ui_Button11, 100);
    lv_obj_set_height(ui_Button11, 50);
    lv_obj_set_align(ui_Button11, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_Button11, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Button11, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Blue);
    ui_object_set_themeable_style_property(ui_Button11, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Blue);

    ui_Image7 = lv_img_create(ui_Button11);
    lv_img_set_src(ui_Image7, &ui_img_1470730272);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image7, -28);
    lv_obj_set_y(ui_Image7, 1);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label24 = lv_label_create(ui_Button11);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label24, 2);
    lv_obj_set_y(ui_Label24, 1);
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "Back");

    lv_obj_add_event_cb(ui_AFCBrush, ui_event_AFCBrush, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_AFCCut, ui_event_AFCCut, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_AFCKick, ui_event_AFCKick, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_AFCPark, ui_event_AFCPark, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_AFCPoop, ui_event_AFCPoop, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BTPrep, ui_event_BTPrep, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BTToolUnload, ui_event_BTToolUnload, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button11, ui_event_Button11, LV_EVENT_ALL, NULL);

}
