// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: BoxTurtle

#include "../ui.h"

void ui_LaneSelect_screen_init(void)
{
    ui_LaneSelect = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_LaneSelect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TitlePanel = lv_obj_create(ui_LaneSelect);
    lv_obj_set_width(ui_TitlePanel, 590);
    lv_obj_set_height(ui_TitlePanel, 50);
    lv_obj_set_x(ui_TitlePanel, 4);
    lv_obj_set_y(ui_TitlePanel, -58);
    lv_obj_set_align(ui_TitlePanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TitlePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TitleText = lv_label_create(ui_TitlePanel);
    lv_obj_set_width(ui_TitleText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TitleText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TitleText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TitleText, "Box Turtle Lane Select");

    ui_ToolButtonContainer = lv_obj_create(ui_LaneSelect);
    lv_obj_remove_style_all(ui_ToolButtonContainer);
    lv_obj_set_width(ui_ToolButtonContainer, 413);
    lv_obj_set_height(ui_ToolButtonContainer, 50);
    lv_obj_set_align(ui_ToolButtonContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ToolButtonContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Tool0Button = lv_btn_create(ui_ToolButtonContainer);
    lv_obj_set_width(ui_Tool0Button, 50);
    lv_obj_set_height(ui_Tool0Button, 50);
    lv_obj_set_x(ui_Tool0Button, -150);
    lv_obj_set_y(ui_Tool0Button, 0);
    lv_obj_set_align(ui_Tool0Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Tool0Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Tool0Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Tool0Button, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Blue);
    ui_object_set_themeable_style_property(ui_Tool0Button, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Blue);
    lv_obj_set_style_bg_img_src(ui_Tool0Button, &ui_img_642937331, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Tool1Button = lv_btn_create(ui_ToolButtonContainer);
    lv_obj_set_width(ui_Tool1Button, 50);
    lv_obj_set_height(ui_Tool1Button, 50);
    lv_obj_set_x(ui_Tool1Button, -50);
    lv_obj_set_y(ui_Tool1Button, 0);
    lv_obj_set_align(ui_Tool1Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Tool1Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Tool1Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Tool1Button, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Blue);
    ui_object_set_themeable_style_property(ui_Tool1Button, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Blue);
    lv_obj_set_style_bg_img_src(ui_Tool1Button, &ui_img_642936306, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Tool2Button = lv_btn_create(ui_ToolButtonContainer);
    lv_obj_set_width(ui_Tool2Button, 50);
    lv_obj_set_height(ui_Tool2Button, 50);
    lv_obj_set_x(ui_Tool2Button, 50);
    lv_obj_set_y(ui_Tool2Button, 0);
    lv_obj_set_align(ui_Tool2Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Tool2Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Tool2Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Tool2Button, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Blue);
    ui_object_set_themeable_style_property(ui_Tool2Button, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Blue);
    lv_obj_set_style_bg_img_src(ui_Tool2Button, &ui_img_642943729, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Tool3Button = lv_btn_create(ui_ToolButtonContainer);
    lv_obj_set_width(ui_Tool3Button, 50);
    lv_obj_set_height(ui_Tool3Button, 50);
    lv_obj_set_x(ui_Tool3Button, 150);
    lv_obj_set_y(ui_Tool3Button, 0);
    lv_obj_set_align(ui_Tool3Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Tool3Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Tool3Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Tool3Button, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Blue);
    ui_object_set_themeable_style_property(ui_Tool3Button, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Blue);
    lv_obj_set_style_bg_img_src(ui_Tool3Button, &ui_img_642942704, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Tool4Button = lv_btn_create(ui_ToolButtonContainer);
    lv_obj_set_width(ui_Tool4Button, 50);
    lv_obj_set_height(ui_Tool4Button, 50);
    lv_obj_set_x(ui_Tool4Button, -150);
    lv_obj_set_y(ui_Tool4Button, 0);
    lv_obj_set_align(ui_Tool4Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Tool4Button, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Tool4Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Tool4Button, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Blue);
    ui_object_set_themeable_style_property(ui_Tool4Button, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Blue);
    lv_obj_set_style_bg_img_src(ui_Tool4Button, &ui_img_642941679, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Tool5Button = lv_btn_create(ui_ToolButtonContainer);
    lv_obj_set_width(ui_Tool5Button, 50);
    lv_obj_set_height(ui_Tool5Button, 50);
    lv_obj_set_x(ui_Tool5Button, -50);
    lv_obj_set_y(ui_Tool5Button, 0);
    lv_obj_set_align(ui_Tool5Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Tool5Button, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Tool5Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Tool5Button, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Blue);
    ui_object_set_themeable_style_property(ui_Tool5Button, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Blue);
    lv_obj_set_style_bg_img_src(ui_Tool5Button, &ui_img_642940654, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Tool6Button = lv_btn_create(ui_ToolButtonContainer);
    lv_obj_set_width(ui_Tool6Button, 50);
    lv_obj_set_height(ui_Tool6Button, 50);
    lv_obj_set_x(ui_Tool6Button, 50);
    lv_obj_set_y(ui_Tool6Button, 0);
    lv_obj_set_align(ui_Tool6Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Tool6Button, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Tool6Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Tool6Button, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Blue);
    ui_object_set_themeable_style_property(ui_Tool6Button, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Blue);
    lv_obj_set_style_bg_img_src(ui_Tool6Button, &ui_img_642948077, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Tool7Button = lv_btn_create(ui_ToolButtonContainer);
    lv_obj_set_width(ui_Tool7Button, 50);
    lv_obj_set_height(ui_Tool7Button, 50);
    lv_obj_set_x(ui_Tool7Button, 150);
    lv_obj_set_y(ui_Tool7Button, 0);
    lv_obj_set_align(ui_Tool7Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Tool7Button, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Tool7Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Tool7Button, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Blue);
    ui_object_set_themeable_style_property(ui_Tool7Button, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Blue);
    lv_obj_set_style_bg_img_src(ui_Tool7Button, &ui_img_642947052, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsButton = lv_btn_create(ui_LaneSelect);
    lv_obj_set_width(ui_SettingsButton, 100);
    lv_obj_set_height(ui_SettingsButton, 50);
    lv_obj_set_x(ui_SettingsButton, -261);
    lv_obj_set_y(ui_SettingsButton, 55);
    lv_obj_set_align(ui_SettingsButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingsButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SettingsButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_SettingsButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Blue);
    ui_object_set_themeable_style_property(ui_SettingsButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Blue);
    lv_obj_set_style_bg_img_src(ui_SettingsButton, &ui_img_settings_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ControlButton = lv_btn_create(ui_LaneSelect);
    lv_obj_set_width(ui_ControlButton, 100);
    lv_obj_set_height(ui_ControlButton, 50);
    lv_obj_set_x(ui_ControlButton, 10);
    lv_obj_set_y(ui_ControlButton, -65);
    lv_obj_set_align(ui_ControlButton, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_ControlButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ControlButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_ControlButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Blue);
    ui_object_set_themeable_style_property(ui_ControlButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Blue);
    lv_obj_set_style_bg_img_src(ui_ControlButton, &ui_img_986727804, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_LaneSelect);
    lv_obj_set_width(ui_Panel4, 68);
    lv_obj_set_height(ui_Panel4, 72);
    lv_obj_set_x(ui_Panel4, 276);
    lv_obj_set_y(ui_Panel4, 48);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image1 = lv_img_create(ui_Panel4);
    lv_img_set_src(ui_Image1, &ui_img_filament_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image1, -20);
    lv_obj_set_y(ui_Image1, -15);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CurrentNozzleTemp = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_CurrentNozzleTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CurrentNozzleTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CurrentNozzleTemp, 10);
    lv_obj_set_y(ui_CurrentNozzleTemp, -15);
    lv_obj_set_align(ui_CurrentNozzleTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CurrentNozzleTemp, "-1");

    ui_Image2 = lv_img_create(ui_Panel4);
    lv_img_set_src(ui_Image2, &ui_img_bed_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image2, -20);
    lv_obj_set_y(ui_Image2, 15);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CurrentBedTemp = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_CurrentBedTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CurrentBedTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CurrentBedTemp, 10);
    lv_obj_set_y(ui_CurrentBedTemp, 15);
    lv_obj_set_align(ui_CurrentBedTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CurrentBedTemp, "-1");

    ui_Printstatus = lv_obj_create(ui_LaneSelect);
    lv_obj_set_width(ui_Printstatus, 271);
    lv_obj_set_height(ui_Printstatus, 50);
    lv_obj_set_align(ui_Printstatus, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_Printstatus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PrintProgressBar = lv_bar_create(ui_Printstatus);
    lv_obj_set_width(ui_PrintProgressBar, 150);
    lv_obj_set_height(ui_PrintProgressBar, 10);
    lv_obj_set_x(ui_PrintProgressBar, 0);
    lv_obj_set_y(ui_PrintProgressBar, 9);
    lv_obj_set_align(ui_PrintProgressBar, LV_ALIGN_CENTER);

    ui_PercentComplete = lv_label_create(ui_Printstatus);
    lv_obj_set_width(ui_PercentComplete, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PercentComplete, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PercentComplete, -8);
    lv_obj_set_y(ui_PercentComplete, 9);
    lv_obj_set_align(ui_PercentComplete, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_PercentComplete, "23%");

    ui_Label2 = lv_label_create(ui_Printstatus);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -13);
    lv_obj_set_y(ui_Label2, 7);
    lv_label_set_text(ui_Label2, "Status:");
    lv_obj_add_flag(ui_Printstatus, LV_OBJ_FLAG_HIDDEN);

    ui_Label3 = lv_label_create(ui_Printstatus);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 2);
    lv_obj_set_y(ui_Label3, -12);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Current-Filename.gcode");

    ui_SwitchStatusPanel = lv_obj_create(ui_LaneSelect);
    lv_obj_set_width(ui_SwitchStatusPanel, 270);
    lv_obj_set_height(ui_SwitchStatusPanel, 50);
    lv_obj_set_align(ui_SwitchStatusPanel, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_SwitchStatusPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label14 = lv_label_create(ui_SwitchStatusPanel);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, -10);
    lv_obj_set_y(ui_Label14, 0);
    lv_obj_set_align(ui_Label14, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label14, "Hub:");

    ui_HubStatus = lv_label_create(ui_SwitchStatusPanel);
    lv_obj_set_width(ui_HubStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HubStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HubStatus, 35);
    lv_obj_set_y(ui_HubStatus, 0);
    lv_obj_set_align(ui_HubStatus, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_HubStatus, "Unloaded");

    ui_ToolStatus = lv_label_create(ui_SwitchStatusPanel);
    lv_obj_set_width(ui_ToolStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ToolStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ToolStatus, 10);
    lv_obj_set_y(ui_ToolStatus, 0);
    lv_obj_set_align(ui_ToolStatus, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_ToolStatus, "Unloaded");

    ui_Label17 = lv_label_create(ui_SwitchStatusPanel);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, -70);
    lv_obj_set_y(ui_Label17, 0);
    lv_obj_set_align(ui_Label17, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Label17, "Tool:");

    ui_GifPanel = lv_obj_create(ui_LaneSelect);
    lv_obj_set_width(ui_GifPanel, 105);
    lv_obj_set_height(ui_GifPanel, 50);
    lv_obj_set_x(ui_GifPanel, 9);
    lv_obj_set_y(ui_GifPanel, -10);
    lv_obj_set_align(ui_GifPanel, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_GifPanel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_GifPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_GifPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_GRAD_COLOR,
                                           _ui_theme_color_Blue);

    lv_obj_add_event_cb(ui_Tool0Button, ui_event_Tool0Button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Tool1Button, ui_event_Tool1Button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Tool2Button, ui_event_Tool2Button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Tool3Button, ui_event_Tool3Button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Tool4Button, ui_event_Tool4Button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Tool5Button, ui_event_Tool5Button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Tool6Button, ui_event_Tool6Button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Tool7Button, ui_event_Tool7Button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ToolButtonContainer, ui_event_ToolButtonContainer, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SettingsButton, ui_event_SettingsButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ControlButton, ui_event_ControlButton, LV_EVENT_ALL, NULL);
    uic_Tool0Button = ui_Tool0Button;
    uic_Tool1Button = ui_Tool1Button;
    uic_Tool2Button = ui_Tool2Button;
    uic_Tool3Button = ui_Tool3Button;
    uic_Tool4Button = ui_Tool4Button;
    uic_Tool5Button = ui_Tool5Button;
    uic_Tool6Button = ui_Tool6Button;
    uic_Tool7Button = ui_Tool7Button;
    uic_CurrentNozzleTemp = ui_CurrentNozzleTemp;

}
