// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: BoxTurtle

#include "../ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel3 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Panel3, 590);
    lv_obj_set_height(ui_Panel3, 50);
    lv_obj_set_x(ui_Panel3, 4);
    lv_obj_set_y(ui_Panel3, -58);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Box = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_Box, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Box, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Box, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Box, "Box Turtle Lane Select");

    ui_Tool0Button = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Tool0Button, 50);
    lv_obj_set_height(ui_Tool0Button, 50);
    lv_obj_set_x(ui_Tool0Button, -150);
    lv_obj_set_y(ui_Tool0Button, 0);
    lv_obj_set_align(ui_Tool0Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Tool0Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Tool0Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Tool0Button, &ui_img_642937331, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Tool1Button = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Tool1Button, 50);
    lv_obj_set_height(ui_Tool1Button, 50);
    lv_obj_set_x(ui_Tool1Button, -50);
    lv_obj_set_y(ui_Tool1Button, 0);
    lv_obj_set_align(ui_Tool1Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Tool1Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Tool1Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Tool1Button, &ui_img_642936306, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Tool2Button = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Tool2Button, 50);
    lv_obj_set_height(ui_Tool2Button, 50);
    lv_obj_set_x(ui_Tool2Button, 50);
    lv_obj_set_y(ui_Tool2Button, 0);
    lv_obj_set_align(ui_Tool2Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Tool2Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Tool2Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Tool2Button, &ui_img_642943729, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Tool3Button = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Tool3Button, 50);
    lv_obj_set_height(ui_Tool3Button, 50);
    lv_obj_set_x(ui_Tool3Button, 150);
    lv_obj_set_y(ui_Tool3Button, 0);
    lv_obj_set_align(ui_Tool3Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Tool3Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Tool3Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Tool3Button, &ui_img_642942704, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button6 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Button6, 100);
    lv_obj_set_height(ui_Button6, 50);
    lv_obj_set_x(ui_Button6, -261);
    lv_obj_set_y(ui_Button6, 55);
    lv_obj_set_align(ui_Button6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Button6, &ui_img_1470730272, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Panel4, 68);
    lv_obj_set_height(ui_Panel4, 32);
    lv_obj_set_x(ui_Panel4, 275);
    lv_obj_set_y(ui_Panel4, 67);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image1 = lv_img_create(ui_Panel4);
    lv_img_set_src(ui_Image1, &ui_img_filament_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image1, -20);
    lv_obj_set_y(ui_Image1, 1);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CurrentNozzleTemp = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_CurrentNozzleTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CurrentNozzleTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CurrentNozzleTemp, 10);
    lv_obj_set_y(ui_CurrentNozzleTemp, 1);
    lv_obj_set_align(ui_CurrentNozzleTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CurrentNozzleTemp, "105");

    lv_obj_add_event_cb(ui_Tool0Button, ui_event_Tool0Button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Tool1Button, ui_event_Tool1Button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Tool2Button, ui_event_Tool2Button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Tool3Button, ui_event_Tool3Button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button6, ui_event_Button6, LV_EVENT_ALL, NULL);
    uic_Tool0Button = ui_Tool0Button;
    uic_Tool1Button = ui_Tool1Button;
    uic_Tool2Button = ui_Tool2Button;
    uic_Tool3Button = ui_Tool3Button;
    uic_CurrentNozzleTemp = ui_CurrentNozzleTemp;

}
